GET http://localhost:5000/api/scooter

###
GET http://localhost:5000/api/scooter/active

###
POST http://localhost:5000/api/scooter/create
Content-Type: application/json

 {
   "id" : "130asd",
 "model": "runner1",
 "location": {"lat":32.08136170392383, "lng":34.775386609946345},
 "year_manufacture": 2019,
 "status": "charged"
 }


###


